version: '3.8'
services:
    backend:
      image: 'backend:1.0'
      build:
        context: backend
        dockerfile: Dockerfile
      environment:
        - PORT=9000
      ports:
        - 9000:9000
